# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'  
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.0'
  inputs:
    packageType: sdk
    version: 3.1.402
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 5.0'
  inputs:
    packageType: sdk
    version: 6.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
    
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk Anonymous'
  inputs:
    packageType: sdk    
    installationPath: $(Agent.ToolsDirectory)/dotnet
pool:
  vmImage: windows-2022

variables:
  buildConfiguration: 'Release'


